### ISSUE TITLE
don't put stuff in the global namespace

### ISSUE THREAD

**Issue by dbgarf** [drigberg/horoscope-generator#2]
everything in /public/js/sentenceGenerator.js is being declared as globally scoped variables or named functions in the global namespace. this is not a good idea. would be much better to create your own namespace to hold all your stuff. this will become necessary when you start extending the functionality of the page and want to include other javascript code. 

some discussion of a decent way to do this here: https://www.kenneth-truyers.net/2013/04/27/javascript-namespaces-and-modules/

**Comment by drigberg** [comment]
I think this has been cleared up!!!! *CLOSED*
